---
- name: copy file
  hosts: localhost
  remote_user: ubuntu
  #vars:
    #authorized_key_list:
      #- name: root
        #authorized_keys:
         #- key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"
           #state: present
  tasks:
    - name: Creating an empty file
      file:
        path: "/home/sample.txt"
        state: touch
      become: true
      become_user: root
      
